# Generated by Django 4.2.1 on 2023-05-17 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_alter_entry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic'),
        ),
    ]
