# Generated by Django 4.2.1 on 2023-05-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_alter_entry_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
