# Generated by Django 4.2.8 on 2023-12-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='created_date',
        ),
    ]
