# Generated by Django 4.2.2 on 2023-07-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_article_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
    ]
