# Generated by Django 4.2.8 on 2023-12-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_articles_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created_dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
