# Generated by Django 4.2.2 on 2023-07-04 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
