# Generated by Django 4.2.8 on 2023-12-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articles_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_dateTime',
            field=models.DateTimeField(),
        ),
    ]
