# Generated by Django 4.2.8 on 2023-12-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articles_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
