# Generated by Django 4.2.2 on 2023-07-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_is_show_article_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=110)),
                ('last_name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
