# Generated by Django 4.2.2 on 2023-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='website_adders',
            field=models.URLField(default='sunlearn.ir'),
            preserve_default=False,
        ),
    ]
