# Generated by Django 4.2.8 on 2023-12-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.EmailField(default='c.gmail.com', max_length=254),
        ),
    ]
