# Generated by Django 4.2.2 on 2023-07-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_person_website_adders'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='score',
            field=models.FloatField(default=11.2),
            preserve_default=False,
        ),
    ]
