# Generated by Django 4.2.8 on 2023-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
