# Generated by Django 4.2.2 on 2023-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_person_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='score_2',
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=5),
            preserve_default=False,
        ),
    ]
