# Generated by Django 4.2.8 on 2023-12-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
