# Generated by Django 4.2.8 on 2023-12-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.person'),
        ),
    ]
