# Generated by Django 4.2.8 on 2023-12-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articles_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.person'),
        ),
    ]
