# Generated by Django 4.2.3 on 2023-08-26 20:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_article_image_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('articles', django.db.models.manager.Manager()),
            ],
        ),
    ]
