# Generated by Django 4.2.3 on 2023-10-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_person_first_name_alter_person_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['score']},
        ),
    ]
