# Generated by Django 4.2.3 on 2023-10-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-age'], 'verbose_name': 'شخص', 'verbose_name_plural': 'اشخاص'},
        ),
    ]
